title: meetingless
description: a framework for productivity
show_downloads: false
show_footer_maintainer: false
google_analytics:
github:
  is_project_page: false
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  # (plugins: jekyll-remote-theme and jekyll-seo-tag)

# GitHub Pages project-site base path
baseurl: "/meetingless"
url: "https://syll20.github.io"